<a href="https://colab.research.google.com/github/hosseinta2/RL/blob/main/RL_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [32]:
import gymnasium as gym
e = gym.make("CartPole-v1")

In [ ]:
obs,info = e.reset()
obs

array([ 0.04000718,  0.02937862,  0.04959688, -0.02769654], dtype=float32)

In [ ]:
e.action_space.sample()


np.int64(1)

In [ ]:
e.observation_space.sample()

array([-4.4680905 , -0.574067  ,  0.00855084,  0.72761846], dtype=float32)

In [ ]:
e.step(0)

(array([ 0.04059475, -0.16641821,  0.04904294,  0.28021306], dtype=float32),
 1.0,
 False,
 False,
 {})

In [ ]:
# testing the environment
import gymnasium as gym

if __name__ == "__main__":
  env = gym.make("CartPole-v1")
  total_reward = 0
  total_steps = 0
  obs, _ = env.reset()
while True:
  action = env.action_space.sample()
  obs,reward,is_done,is_trunc,_ = env.step(action)
  total_reward+=reward
  total_steps += 1
  if is_done==True:
    break
print(total_reward,"rewards in ",total_steps, "steps")

11.0 rewards in  11 steps


In [53]:
import random
from gymnasium.wrappers import RecordVideo
from IPython.display import Video
import glob
class RandomActionWrapper(gym.ActionWrapper):
  def __init__(self, env: gym.Env, epsilon: float= 0.5):
    super(RandomActionWrapper,self).__init__(env)
    self.epsilon = epsilon
  def action(self, action: gym.core.WrapperActType):
    if random.random()<self.epsilon:
       action = self.env.action_space.sample()
       print(action)
    return action
if __name__ == "__main__":
  env = RandomActionWrapper(gym.make("CartPole-v1", render_mode = "rgb_array"))
  env = RecordVideo(env,video_folder="videos",episode_trigger=lambda episode_id: True)

  obs,_ = env.reset()
  total_reward = 0

  while True:
    obs,reward,done,_,_ = env.step(0)
    total_reward += reward
    if done:
      break
  print(total_reward)
env.close()


video_path = glob.glob("videos/*.mp4")[0]
Video(video_path, embed=True)

1
1
1
0
0
1
1
1
0
1
0
1
1
0
25.0
