<a href="https://colab.research.google.com/github/hosseinta2/RL/blob/main/RL_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import gymnasium as gym
e = gym.make("CartPole-v1")

In [ ]:
obs,info = e.reset()
obs

array([-0.0298307 ,  0.02047397, -0.02204562,  0.00829435], dtype=float32)

In [ ]:
e.action_space.sample()


np.int64(1)

In [ ]:
e.observation_space.sample()

array([-4.117378  , -0.43619788,  0.24572593, -0.11987072], dtype=float32)

In [ ]:
e.step(0)

(array([-0.37939993, -2.7073014 ,  0.53332573,  4.554478  ], dtype=float32),
 0.0,
 True,
 False,
 {})

In [ ]:
import gymnasium as gym

if __name__ == "__main__":
  env = gym.make("CartPole-v1")
  total_reward = 0
  total_steps = 0
  obs, _ = env.reset()
while True:
  action = env.action_space.sample()
  obs,reward,is_done,is_trunc,_ = env.step(action)
  total_reward+=reward
  total_steps += 1
  if is_done==True:
    break
print(total_reward,"rewards in ",total_steps, "steps")

10.0 rewards in  10 steps
